<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>BingLan.WidgetHost.Sample</AssemblyName>
    <RootNamespace>BingLan.WidgetHost.Sample</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BingLan.WidgetHost.Wpf/BingLan.WidgetHost.Wpf.csproj"/>
  </ItemGroup>
</Project>
